import {
  BigBannerProductsInterface,
  CategoryInterface,
  ProductInterface,
} from '../shared/interfaces/interfaces';

export const Categories: CategoryInterface[] = [
  { name: 'Phones', icon: 'smartphone' },
  { name: 'Smart Watches', icon: 'watch' },
  { name: 'Cameras', icon: 'local_see' },
  { name: 'Headphones', icon: 'headphones' },
  { name: 'Computers', icon: 'computer' },
  { name: 'Gaming', icon: 'sports_esports' },
];

export const Products: ProductInterface[] = [
  {
    header: 'Apple iPhone 14 Pro Max',
    price: 90,
    oldPrice: 100,
    isFavorite: false,
    image: '',
    id: '1',
    type: ['newArrival'],
    categories: [],
    options: ['128GB', '256GB', '512GB', '1TB'],
    details:
      'Enhanced capabilities thanks toan enlarged display of 6.7 inchesand work without rechargingthroughout the day. Incredible photosas in weak, yesand in bright lightusing the new systemwith two cameras more...',
    parameters: [
      { name: 'Screen size', value: '6.7"', icon: 'smartphone' },
      { name: 'CPU', value: 'Apple A14 Bionic', icon: 'memory' },
      { name: 'Number of cores', value: '6', icon: 'memory' },
      { name: 'Main camera', value: '48 - 12 - 12MP', icon: 'photo_camera' },
      { name: 'Front camera', value: '12MP', icon: 'photo_camera' },
      {
        name: 'Battery capacity',
        value: '4332 mAh',
        icon: 'battery_charging_full',
      },
    ],
  },
  {
    header: 'Blackmagic Pocket Cinema Camera 6k',
    price: 253,
    oldPrice: 283,
    isFavorite: false,
    image: '',
    id: '2',
    type: ['newArrival'],
    categories: [],
  },
  {
    header: 'Apple Watch Series 9',
    price: 39,
    oldPrice: 59,
    isFavorite: false,
    image: '',
    id: '3',
    type: ['newArrival'],
    categories: [],
  },
  {
    header: 'AirPods Max Silver',
    price: 54,
    oldPrice: 64,
    isFavorite: false,
    image: '',
    id: '4',
    type: ['newArrival'],
    categories: [],
  },
  {
    header: 'Samsung Galaxy Watch6 Classic',
    price: 369,
    isFavorite: false,
    image: '',
    id: '5',
    type: ['newArrival'],
    categories: [],
  },
  {
    header: 'Galaxy Z Fold5 Unlocked',
    price: 1799,
    isFavorite: false,
    image: '',
    id: '6',
    type: ['newArrival'],
    categories: [],
  },
  {
    header: 'Galaxy Buds FE',
    price: 99.99,
    isFavorite: false,
    image: '',
    id: '7',
    type: ['featured'],
    categories: [],
  },
  {
    header: 'Apple iPad 9 10.2"',
    price: 398,
    isFavorite: false,
    image: '',
    id: '8',
    type: ['featured'],
    categories: [],
  },
  {
    header: 'Sony PlayStation 5',
    price: 499.99,
    isFavorite: false,
    image: '',
    id: '9',
    type: ['bestSeller'],
    categories: [],
  },
  {
    header: 'Xbox Series X 1TB',
    price: 499,
    isFavorite: false,
    image: '',
    id: '10',
    type: ['bestSeller'],
    categories: [],
  },
  {
    header: 'Nintendo Switch OLED',
    price: 349.99,
    isFavorite: false,
    image: '',
    id: '11',
    type: ['newArrival'],
    categories: [],
  },
  {
    header: 'DJI Mavic Air 2 Fly',
    price: 999,
    isFavorite: false,
    image: '',
    id: '12',
    type: ['featured'],
    categories: [],
  },
  {
    header: 'GoPro HERO10',
    price: 499.99,
    isFavorite: false,
    image: '',
    id: '13',
    type: ['featured'],
    categories: [],
  },
  {
    header: 'Canon EOS R5 Mirrorless Camera',
    price: 3899,
    isFavorite: false,
    image: '',
    id: '14',
    type: ['newArrival'],
    categories: [],
  },
  {
    header: 'Bose QuietComfort 45 Wireless Noise Cancelling Headphones',
    price: 329.95,
    isFavorite: false,
    image: '',
    id: '15',
    type: ['bestSeller'],
    categories: [],
  },
  {
    header: 'Samsung 85" QN90A Neo QLED 4K Smart TV',
    price: 4499.99,
    isFavorite: false,
    image: '',
    id: '16',
    type: ['featured'],
    categories: [],
  },
  {
    header: 'Sony WH-1000XM4 Wireless Noise Cancelling Headphones',
    price: 348,
    isFavorite: false,
    image: '',
    id: '17',
    type: ['bestSeller'],
    categories: [],
  },
  {
    header: 'LG CX 55" 4K Smart OLED TV',
    price: 1599.99,
    isFavorite: false,
    image: '',
    id: '18',
    type: ['featured'],
    categories: [],
  },
];

export const bigBannerProducts: BigBannerProductsInterface[] = [
  {
    header: 'Apple iPhone 14 Pro Max',
    price: 900,
    isFavorite: false,
    image: '',
    id: '1',
    categories: [],
    description:
      "<div class='flex flex-col items-center justify-center gap-4'><div class='text-sm '>The Apple iPhone 14 Pro Max in Deep Purple features 128GB of storage capacity. Experience powerful performance and stunning visuals with its advanced technology and sleek design.</div><button class='rounded-md border-[.0938rem] border-black px-14 py-4'>Shop Now</button></div>",
  },
  {
    header: 'Blackmagic Pocket Cinema Camera 6k',
    price: 2535,
    isFavorite: false,
    image: '',
    id: '2',
    categories: [],
    description:
      "<div class='flex flex-col items-center justify-center gap-4'><div class='text-sm '>Capture stunning cinematic footage with the Blackmagic Pocket Cinema Camera 6k. Featuring high-resolution recording capabilities and advanced image processing, it's the perfect tool for professional filmmakers.</div><button class='rounded-md border-[.0938rem] border-black px-14 py-4'>Shop Now</button></div>",
  },
  {
    header: 'Apple Watch Series 9 GPS',
    price: 399,
    isFavorite: false,
    image: '',
    id: '3',
    categories: [],
    description:
      "<div class='flex flex-col items-center justify-center gap-4'><div class='text-sm '>Stay connected and track your fitness goals with the Apple Watch Series 9 GPS. Its sleek design and advanced features make it the perfect companion for an active lifestyle.</div><button class='rounded-md border-[.0938rem] border-black px-14 py-4'>Shop Now</button></div>",
  },
  {
    header: 'AirPods Max',
    price: 549,
    isFavorite: false,
    image: '',
    id: '4',
    categories: [],
    description:
      "<div class='flex flex-col items-center justify-center gap-4'><div class='text-sm '>Experience immersive audio quality with the AirPods Max in Silver. Featuring advanced technology and a comfortable design, they're perfect for enjoying your favorite music and podcasts.</div><button class='rounded-md border-[.0938rem] border-black px-14 py-4'>Shop Now</button></div>",
  },
];
